"""nikmk

Revision ID: 1f712d8818c5
Revises: 13622b495465
Create Date: 2024-01-25 12:35:36.992579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f712d8818c5'
down_revision: Union[str, None] = '13622b495465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'appointments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'lawyers', ['lawyer_id'], ['id'])
    op.drop_index('evaluations_ibfk_2', table_name='evaluations')
    op.create_foreign_key(None, 'evaluations', 'lawyers', ['lawyer_id'], ['id'])
    op.create_foreign_key(None, 'evaluations', 'users', ['user_id'], ['id'])
    op.drop_index('lawyer_category_ibfk_1', table_name='lawyer_category')
    op.create_foreign_key(None, 'lawyer_category', 'categories', ['category_id'], ['id'], ondelete='NO ACTION')
    op.create_foreign_key(None, 'lawyer_category', 'lawyers', ['Lawyer_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lawyer_category', type_='foreignkey')
    op.drop_constraint(None, 'lawyer_category', type_='foreignkey')
    op.create_index('lawyer_category_ibfk_1', 'lawyer_category', ['category_id'], unique=False)
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.create_index('evaluations_ibfk_2', 'evaluations', ['lawyer_id'], unique=False)
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    # ### end Alembic commands ###
